# BERT
 - GPT and BERT are both based on the Transformer architecture, but they are designed for different goals.
 - GPT is mainly designed for:    text generation, while BERT is mainly designed for: language understanding
 - GPT uses a Transformer decoder with: left-to-right masked attention, This means each token can only see previous tokens.
    - Example: "The sky is" , GPT predicts: blue, by generating one token at a time.
    - To generate text correctly, GPT must NOT see future tokens. So GPT uses: masked self-attention, inside the Transformer decoder.
    - Because GPT learns next-token prediction, it becomes very strong at:
      - text generation, chatbots, code generation, story writing, summarization
      - However, GPT cannot see future words during representation learning.
 - BERT uses a Transformer encoder with: bidirectional self-attention
   - Each token can see: previous words, future words simultaneously.
   - Example: "The animal didn't cross the road because it was tired." BERT can understand: it = animal, using the full sentence context.
   - BERT is trained using: Masked Language Modeling, where random words are hidden: "The cat sat on the [MASK]."
   - The model predicts the missing word.
   - This creates strong contextual sentence representations.
   - Because BERT sees both directions of context, it performs extremely well on:
     - sentence classification
     - question answering
     - token classification
     - named entity recognition
     - semantic similarity
 - GPT is usually stronger for: generation tasks
   - because causal masking naturally supports:
     - next-token prediction
     - autoregressive generation
 - BERT is usually stronger for understanding tasks, because bidirectional attention gives richer semantic representations.
 - Another important difference is: GPT generates text sequentially: token1 → token2 → token3
 - while BERT processes the entire sentence simultaneously.
 - In summary, GPT behaves more like a writer, predicting what comes next.
 - BERT behaves more like: a reader, deeply understanding the whole sentence before making predictions.

## Why Decoder for GPT?
 - Decoder attention works like: token_i, can only attend to: previous tokens
 - Example: I love machine, while predicting: learning, GPT cannot see: learning, before prediction.
 - used decoder for both the pretrained and fine-tuning models
 - Aggressive text generation does not pay attention to future text.
 - generate token sequentially
 - 
## Why Encoder for BERT?
 - BERT sees FULL sentence, Best for: understanding, because all tokens see full context.
 - BERT is NOT generating next tokens step-by-step
 - BERT predicts ONE masked position
 - Encoder self-attention is: bidirectional,
 - used encoder for both the pretrained and fine-tuning models
 - generate token simultaneously 
 - This helps BERT deeply understand:
    - sentence meaning
    - context
    - relationships
 - In BERT: every token can attend to every other word in the sentence, because BERT uses bidirectional self-attention inside the Transformer encoder.
   - This means there is: no causal/future mask in the encoder


![My Image](image/4.png)

# BERT Pretraining and Fine-Tuning Figure Explanation

This figure shows the two major stages of BERT:

1. Pre-training  
2. Fine-tuning

The important idea is:

```text
the same pretrained BERT encoder
```

is reused for many NLP tasks during fine-tuning.

A task-specific output layer is added for each task, while both the encoder weights and the output layer are updated together during fine-tuning.

---

# Left Side — Pre-training

## Input

BERT receives:

```text
Sentence A + Sentence B
```

Example:

```text
Sentence A:
"The cat sat on the mat."

Sentence B:
"It was sleeping."
```

Input format:

```text
[CLS] Sentence A [SEP] Sentence B [SEP]
```

---

# Special Tokens

| Token | Meaning |
|---|---|
| `[CLS]` | classification token |
| `[SEP]` | separator token |

---

# Embeddings at Bottom

Bottom boxes:

```text
Tok1 Tok2 Tok3 ...
```

are:
- input tokens

Yellow boxes:

```text
E[CLS], E1, E2 ...
```

are:
- token embeddings
- positional embeddings
- segment embeddings

combined together.

These embeddings enter the BERT encoder.

---

# Inside BERT

The blue block:

```text
BERT
```

contains:
- stacked Transformer encoder layers
- bidirectional self-attention

Every token can attend to:
- left words
- right words

simultaneously.

---

# Pretraining Task 1 — Masked Language Modeling (Mask LM)

Some words are hidden.

Example:

```text
"The cat sat on the [MASK]."
```

BERT predicts:

```text
mat
```

Red arrows labeled:

```text
Mask LM
```

show prediction of masked tokens.

---

# Why MLM Helps

BERT learns:
- grammar
- semantics
- sentence meaning
- contextual relationships

using BOTH directions of context.

---

# Pretraining Task 2 — NSP (Next Sentence Prediction)

Top-left red arrow:

```text
NSP
```

BERT predicts whether:

```text
Sentence B logically follows Sentence A
```

---

## Positive Example

```text
A: "I went outside."
B: "It was raining."
```

---

## Negative Example

```text
A: "I went outside."
B: "Bananas are yellow."
```

This helps BERT learn:
- sentence relationships
- discourse understanding

---

# Right Side — Fine-Tuning

After pretraining:

```text
same pretrained BERT model
```

is reused for many NLP tasks.

Examples shown:

| Task | Meaning |
|---|---|
| MNLI | entailment |
| NER | named entity recognition |
| SQuAD | question answering |

---

# Fine-Tuning for Sentence Classification (MNLI)

Uses:

```text
[CLS] representation
```

Flow:

```text
Input
   ↓
BERT
   ↓
[CLS]
   ↓
Classifier
```

Predict:
- entailment
- contradiction
- neutral

---

# Fine-Tuning for NER

BERT outputs:

```text
one contextual vector per token
```

Then token classifier predicts:

| Token | Label |
|---|---|
| John | PERSON |
| Seattle | LOCATION |

---

# Fine-Tuning for QA (SQuAD)

Input:

```text
Question + Paragraph
```

BERT predicts:
- start token
- end token

of answer span.

Top arrows:

```text
Start/End Span
```

---

## Example

Context:

```text
"The sky is blue."
```

Question:

```text
"What color is the sky?"
```

BERT predicts:

```text
blue
```

by selecting token span positions.

---

# Main Message of Figure

BERT learns:

```text
general language understanding
```

during pretraining.

Then the SAME encoder is adapted to:
- QA
- classification
- NER
- similarity
- many NLP tasks

through fine-tuning.

---

# Key Contribution

Before BERT:
- many task-specific models
- separate architectures

BERT showed:

```text
one pretrained bidirectional encoder
```

can work for MANY downstream tasks with small modifications.

---

# Big Picture

```text
Large Text Corpus
      ↓
Pretrain BERT
      ↓
Learn Language Representations
      ↓
Fine-Tune for Specific Tasks
      ↓
State-of-the-Art NLP Performance
```

In [5]:
import torch

# -----------------------------
# Tiny vocabulary
# -----------------------------

vocab = {
    "[PAD]": 0,
    "[CLS]": 1,
    "[SEP]": 2,
    "[MASK]": 3,
    "the": 4,
    "cat": 5,
    "sat": 6,
    "on": 7,
    "mat": 8,
    "it": 9,
    "was": 10,
    "sleeping": 11,
}

id_to_word = {v: k for k, v in vocab.items()}

PAD = vocab["[PAD]"]
CLS = vocab["[CLS]"]
SEP = vocab["[SEP]"]
MASK = vocab["[MASK]"]

# -----------------------------
# Two sentences
# -----------------------------

sentence_a = ["the", "cat", "sat"]
sentence_b = ["it", "was", "sleeping"]

# ---------------------------------------------------
# Build BERT input
# [CLS] sentenceA [SEP] sentenceB [SEP]
# ---------------------------------------------------

tokens = (
    [CLS]
    + [vocab[w] for w in sentence_a]
    + [SEP]
    + [vocab[w] for w in sentence_b]
    + [SEP]
)

input_ids = torch.tensor([tokens])

print("Input IDs:")
print(input_ids)

# ---------------------------------------------------
# Convert back to tokens
# ---------------------------------------------------

print("\nTokens:")

decoded = [id_to_word[i] for i in input_ids[0].tolist()]
print(decoded)

# ---------------------------------------------------
# Segment IDs
# Sentence A = 0
# Sentence B = 1
# ---------------------------------------------------

token_type_ids = torch.tensor([
    [
        0,  # [CLS]
        0, 0, 0,  # sentence A
        0,  # [SEP]

        1, 1, 1,  # sentence B
        1   # [SEP]
    ]
])

print("\nSegment IDs:")
print(token_type_ids)

# ---------------------------------------------------
# Attention mask
# 1 = real token
# 0 = padding
# ---------------------------------------------------

attention_mask = torch.tensor([
    [1] * len(tokens)
])

print("\nAttention Mask:")
print(attention_mask)


mlm_labels = torch.tensor([
    [-100, -100, -100, -100, -100, -100, -100, vocab["sleeping"], -100]
])

Input IDs:
tensor([[ 1,  4,  5,  6,  2,  9, 10, 11,  2]])

Tokens:
['[CLS]', 'the', 'cat', 'sat', '[SEP]', 'it', 'was', 'sleeping', '[SEP]']

Segment IDs:
tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1]])

Attention Mask:
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [9]:
# -----------------------------
# 3. Tiny BERT model
# -----------------------------

class TinyBERT(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model=32,
        num_heads=4,
        num_layers=2,
        max_len=32,
        num_segments=2,
        num_classes=2,
    ):
        super().__init__()

        self.token_embedding = nn.Embedding(vocab_size, d_model)
        self.position_embedding = nn.Embedding(max_len, d_model)
        self.segment_embedding = nn.Embedding(num_segments, d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=num_heads,
            dim_feedforward=64,
            batch_first=True
        )

        self.encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.mlm_head = nn.Linear(d_model, vocab_size)
        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, input_ids, token_type_ids, attention_mask):
        batch_size, seq_len = input_ids.shape

        positions = torch.arange(seq_len, device=input_ids.device)
        positions = positions.unsqueeze(0).expand(batch_size, seq_len)

        x = (
            self.token_embedding(input_ids)
            + self.position_embedding(positions)
            + self.segment_embedding(token_type_ids)
        )

        # PyTorch expects True for padding positions
        padding_mask = attention_mask == 0

        x = self.encoder(
            x,
            src_key_padding_mask=padding_mask
        )

        # MLM prediction for every token
        mlm_logits = self.mlm_head(x)

        # Classification prediction from [CLS]
        cls_hidden = x[:, 0, :]
        cls_logits = self.classifier(cls_hidden)

        return mlm_logits, cls_logits

In [7]:
# -----------------------------
# 4. Train TinyBERT
# -----------------------------

model = TinyBERT(
    vocab_size=len(vocab),
    d_model=32,
    num_heads=4,
    num_layers=2,
    num_classes=2
)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

mlm_loss_fn = nn.CrossEntropyLoss(ignore_index=-100)
cls_loss_fn = nn.CrossEntropyLoss()

for epoch in range(200):
    model.train()

    mlm_logits, cls_logits = model(
        input_ids=input_ids,
        token_type_ids=token_type_ids,
        attention_mask=attention_mask
    )

    mlm_loss = mlm_loss_fn(
        mlm_logits.view(-1, len(vocab)),
        mlm_labels.view(-1)
    )

    cls_loss = cls_loss_fn(cls_logits, cls_label)

    loss = mlm_loss + cls_loss

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 50 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 50, Loss: 0.0003
Epoch 100, Loss: 0.0002
Epoch 150, Loss: 0.0001
Epoch 200, Loss: 0.0001


In [10]:
# -----------------------------
# 5. Test masked word prediction
# -----------------------------

model.eval()

with torch.no_grad():
    mlm_logits, cls_logits = model(
        input_ids=input_ids,
        token_type_ids=token_type_ids,
        attention_mask=attention_mask
    )

mask_position = 5

predicted_id = mlm_logits[0, mask_position].argmax().item()

print("Input:")
print("[CLS] the cat sat on [MASK] [SEP]")

print("\nPredicted masked word:")
print(id_to_word[predicted_id])

print("\nClassification logits:")
print(cls_logits)

Input:
[CLS] the cat sat on [MASK] [SEP]

Predicted masked word:
sleeping

Classification logits:
tensor([[ 5.7908, -4.7100]])
